services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - 5500:5500
    env_file:
      - path: ./apps/backend/.env
        required: true

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5500/api
    ports:
      - 8080:8080
